name: Build-Website
on: [push, workflow_dispatch]

jobs:
  build-site:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install doxygen graphviz --no-install-recommends
      - name: Clone Engine
        run: git clone https://github.com/RavEngine/RavEngine --depth=1 
      - name: Generate docs
        run: doxygen doxyconfig
      - name: Fixup
        run: |
         mv doxyout/html ./_site 
      - name: Fix permissions
        run: |
         chmod -c -R +rX "_site/" | while read line; do
           echo "::warning title=Invalid file permissions automatically fixed::$line"
         done
      - name: Upload 
        uses: actions/upload-pages-artifact@v2

# Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build-site

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
